// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5M_94wPWcinNIvVmV8NybFOX-hx9WSS4',
    appId: '1:316715206560:web:c255f4bee26954eff106c5',
    messagingSenderId: '316715206560',
    projectId: 'mrrobot-coffeemaker',
    authDomain: 'mrrobot-coffeemaker.firebaseapp.com',
    databaseURL: 'https://mrrobot-coffeemaker-default-rtdb.firebaseio.com',
    storageBucket: 'mrrobot-coffeemaker.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_-1uc-HAUQvv76aIxfpcZUzo_29pMMNs',
    appId: '1:316715206560:android:8bbcc09babdd5f6af106c5',
    messagingSenderId: '316715206560',
    projectId: 'mrrobot-coffeemaker',
    databaseURL: 'https://mrrobot-coffeemaker-default-rtdb.firebaseio.com',
    storageBucket: 'mrrobot-coffeemaker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVNUpHT75AEtDF1bGHiiGC-BjPiZQlsKo',
    appId: '1:316715206560:ios:b7f2ea19fde63f5af106c5',
    messagingSenderId: '316715206560',
    projectId: 'mrrobot-coffeemaker',
    databaseURL: 'https://mrrobot-coffeemaker-default-rtdb.firebaseio.com',
    storageBucket: 'mrrobot-coffeemaker.appspot.com',
    iosClientId: '316715206560-1tqb4d6qbpnno3rc2fio2pl8grf697bl.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeMaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVNUpHT75AEtDF1bGHiiGC-BjPiZQlsKo',
    appId: '1:316715206560:ios:87a93120c1e8011df106c5',
    messagingSenderId: '316715206560',
    projectId: 'mrrobot-coffeemaker',
    databaseURL: 'https://mrrobot-coffeemaker-default-rtdb.firebaseio.com',
    storageBucket: 'mrrobot-coffeemaker.appspot.com',
    iosClientId: '316715206560-ibl056ghh6jh7g5iojm70gngqdif59b4.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeMaker.RunnerTests',
  );
}
